/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kavishna
 */
public class managePostgraduateprogram extends javax.swing.JFrame {

    /**
     * Creates new form managePostgraduateprogram
     */
    public managePostgraduateprogram() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        addp = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        upp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        vp = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        dp = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        mid = new javax.swing.JPanel();
        addL = new javax.swing.JPanel();
        progl1 = new javax.swing.JLabel();
        prog1 = new javax.swing.JLabel();
        prog2 = new javax.swing.JLabel();
        prog3 = new javax.swing.JLabel();
        prog4 = new javax.swing.JLabel();
        prog5 = new javax.swing.JLabel();
        pno1 = new javax.swing.JTextField();
        pname1 = new javax.swing.JTextField();
        sdate1 = new javax.swing.JTextField();
        du1 = new javax.swing.JTextField();
        price1 = new javax.swing.JTextField();
        addButt = new javax.swing.JButton();
        close1 = new javax.swing.JButton();
        updateL = new javax.swing.JPanel();
        progl2 = new javax.swing.JLabel();
        progl3 = new javax.swing.JLabel();
        prog7 = new javax.swing.JLabel();
        prog9 = new javax.swing.JLabel();
        prog10 = new javax.swing.JLabel();
        prog11 = new javax.swing.JLabel();
        prog12 = new javax.swing.JLabel();
        pid1 = new javax.swing.JTextField();
        uname1 = new javax.swing.JTextField();
        usdate1 = new javax.swing.JTextField();
        udu1 = new javax.swing.JTextField();
        upri1 = new javax.swing.JTextField();
        jButt1 = new javax.swing.JButton();
        jButt2 = new javax.swing.JButton();
        jButt3 = new javax.swing.JButton();
        jButt4 = new javax.swing.JButton();
        close2 = new javax.swing.JButton();
        viewL = new javax.swing.JPanel();
        vLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        close3 = new javax.swing.JButton();
        deleteL = new javax.swing.JPanel();
        prol6 = new javax.swing.JLabel();
        prog13 = new javax.swing.JLabel();
        prog14 = new javax.swing.JLabel();
        deletepr = new javax.swing.JTextField();
        deleteBut = new javax.swing.JButton();
        close4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel17.setBackground(new java.awt.Color(204, 204, 204));

        jPanel18.setBackground(new java.awt.Color(153, 153, 153));

        addp.setBackground(new java.awt.Color(153, 153, 153));
        addp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addpMousePressed(evt);
            }
        });

        jLabel11.setText("Add program");

        javax.swing.GroupLayout addpLayout = new javax.swing.GroupLayout(addp);
        addp.setLayout(addpLayout);
        addpLayout.setHorizontalGroup(
            addpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        addpLayout.setVerticalGroup(
            addpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        upp.setBackground(new java.awt.Color(153, 153, 153));
        upp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                uppMousePressed(evt);
            }
        });

        jLabel4.setText("Update program");

        javax.swing.GroupLayout uppLayout = new javax.swing.GroupLayout(upp);
        upp.setLayout(uppLayout);
        uppLayout.setHorizontalGroup(
            uppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        uppLayout.setVerticalGroup(
            uppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uppLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vp.setBackground(new java.awt.Color(153, 153, 153));
        vp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                vpMousePressed(evt);
            }
        });

        jLabel12.setText("View program");

        javax.swing.GroupLayout vpLayout = new javax.swing.GroupLayout(vp);
        vp.setLayout(vpLayout);
        vpLayout.setHorizontalGroup(
            vpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        vpLayout.setVerticalGroup(
            vpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        dp.setBackground(new java.awt.Color(153, 153, 153));
        dp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                dpMousePressed(evt);
            }
        });

        jLabel13.setText("Delete program");

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(addp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(upp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(upp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(dp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mid.setBackground(new java.awt.Color(204, 204, 204));
        mid.setLayout(new java.awt.CardLayout());

        addL.setBackground(new java.awt.Color(204, 204, 204));

        progl1.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        progl1.setText("Add new  postgraduate degree program");

        prog1.setText("Program No");

        prog2.setText("Program Name");

        prog3.setText("Strating Date");

        prog4.setText("Duration");

        prog5.setText("Price");

        addButt.setText("Add");
        addButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtActionPerformed(evt);
            }
        });

        close1.setText("Close");
        close1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addLLayout = new javax.swing.GroupLayout(addL);
        addL.setLayout(addLLayout);
        addLLayout.setHorizontalGroup(
            addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progl1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(addLLayout.createSequentialGroup()
                            .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(prog1)
                                .addComponent(prog2)
                                .addComponent(prog3)
                                .addComponent(prog4)
                                .addComponent(prog5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(62, 62, 62)
                            .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(du1)
                                .addComponent(price1, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                                .addComponent(pno1)
                                .addComponent(pname1)
                                .addComponent(sdate1)))
                        .addComponent(addButt)
                        .addComponent(close1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        addLLayout.setVerticalGroup(
            addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(progl1)
                .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addLLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(prog1)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pno1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)))
                .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prog2)
                    .addComponent(pname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prog3)
                    .addComponent(sdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prog4)
                    .addComponent(du1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(addLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prog5))
                .addGap(36, 36, 36)
                .addComponent(addButt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(close1)
                .addGap(22, 22, 22))
        );

        mid.add(addL, "card2");

        updateL.setBackground(new java.awt.Color(204, 204, 204));

        progl2.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        progl2.setText("Update  postgraduate degree program");

        progl3.setText("Enter program no where you want to make a change");

        prog7.setText("Program No");

        prog9.setText(" Update Program Name");

        prog10.setText(" Update Strating Date");

        prog11.setText(" Update Duration");

        prog12.setText(" Update Price");

        jButt1.setText("Update");
        jButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt1ActionPerformed(evt);
            }
        });

        jButt2.setText("Update");
        jButt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt2ActionPerformed(evt);
            }
        });

        jButt3.setText("Update");
        jButt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt3ActionPerformed(evt);
            }
        });

        jButt4.setText("Update");
        jButt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButt4ActionPerformed(evt);
            }
        });

        close2.setText("Close");
        close2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout updateLLayout = new javax.swing.GroupLayout(updateL);
        updateL.setLayout(updateLLayout);
        updateLLayout.setHorizontalGroup(
            updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(progl3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(progl2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(updateLLayout.createSequentialGroup()
                        .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(prog7)
                            .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(prog9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(prog10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(prog11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prog12, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pid1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateLLayout.createSequentialGroup()
                                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(upri1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(udu1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(usdate1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(uname1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButt1)
                                    .addComponent(jButt2)
                                    .addComponent(jButt3)
                                    .addComponent(jButt4)
                                    .addComponent(close2, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        updateLLayout.setVerticalGroup(
            updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(progl2)
                .addGap(18, 18, 18)
                .addComponent(progl3)
                .addGap(36, 36, 36)
                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prog7)
                    .addComponent(pid1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prog9)
                    .addComponent(uname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButt1))
                .addGap(31, 31, 31)
                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prog10)
                    .addComponent(usdate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButt2))
                .addGap(30, 30, 30)
                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prog11)
                    .addComponent(udu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButt3))
                .addGap(26, 26, 26)
                .addGroup(updateLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prog12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upri1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButt4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(close2))
        );

        mid.add(updateL, "card3");

        viewL.setBackground(new java.awt.Color(204, 204, 204));

        vLabel7.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        vLabel7.setText("View postgraduate degree programs");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Program No", "Program Name", "Starting Date", "Duration", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        close3.setText("Close");
        close3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewLLayout = new javax.swing.GroupLayout(viewL);
        viewL.setLayout(viewLLayout);
        viewLLayout.setHorizontalGroup(
            viewLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(vLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewLLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close3)
                .addContainerGap())
            .addGroup(viewLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewLLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        viewLLayout.setVerticalGroup(
            viewLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLLayout.createSequentialGroup()
                .addComponent(vLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 501, Short.MAX_VALUE)
                .addComponent(close3))
            .addGroup(viewLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(viewLLayout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGap(51, 51, 51)))
        );

        mid.add(viewL, "card4");

        deleteL.setBackground(new java.awt.Color(204, 204, 204));

        prol6.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        prol6.setText("Delete postgraduate degree program");

        prog13.setText("Enter Progam no you want to delete");

        prog14.setText("Program No");

        deleteBut.setText("Delete");
        deleteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButActionPerformed(evt);
            }
        });

        close4.setText("Close");
        close4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteLLayout = new javax.swing.GroupLayout(deleteL);
        deleteL.setLayout(deleteLLayout);
        deleteLLayout.setHorizontalGroup(
            deleteLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(deleteLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(close4)
                    .addGroup(deleteLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(deleteLLayout.createSequentialGroup()
                            .addComponent(prog14)
                            .addGap(46, 46, 46)
                            .addComponent(deletepr, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(deleteBut))
                        .addComponent(prog13, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(prol6, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        deleteLLayout.setVerticalGroup(
            deleteLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(prol6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prog13)
                .addGap(51, 51, 51)
                .addGroup(deleteLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prog14)
                    .addComponent(deletepr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 367, Short.MAX_VALUE)
                .addComponent(close4)
                .addGap(20, 20, 20))
        );

        mid.add(deleteL, "card5");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addpMousePressed
        addp.setBackground(new Color(204, 204, 204));
        upp.setBackground(new Color(153, 153, 153));
        vp.setBackground(new Color(153, 153, 153));
        dp.setBackground(new Color(153, 153, 153));

        addL.setVisible(true);
        updateL.setVisible(false);
        viewL.setVisible(false);
        deleteL.setVisible(false);
    }//GEN-LAST:event_addpMousePressed

    private void uppMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uppMousePressed
        addp.setBackground(new Color(153, 153, 153));
        upp.setBackground(new Color(204, 204, 204));
        vp.setBackground(new Color(153, 153, 153));
        dp.setBackground(new Color(153, 153, 153));

        addL.setVisible(false);
        updateL.setVisible(true);
        viewL.setVisible(false);
        deleteL.setVisible(false);
    }//GEN-LAST:event_uppMousePressed

    private void vpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vpMousePressed
        addp.setBackground(new Color(153, 153, 153));
        upp.setBackground(new Color(153, 153, 153));
        vp.setBackground(new Color(204, 204, 204));
        dp.setBackground(new Color(153, 153, 153));

        addL.setVisible(false);
        updateL.setVisible(false);
        viewL.setVisible(true);
        deleteL.setVisible(false);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/New_Database", "root", "ng1996kt");

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from postgraduate");
            DefaultTableModel clear = (DefaultTableModel) (jTable2.getModel());
            clear.setRowCount(0);

            while (rs.next()) {
                int i = rs.getInt(1);
                String d = rs.getString(2);
                String e = rs.getString(3);
                String f = rs.getString(4);
                String h = rs.getString(5);
                DefaultTableModel model = (DefaultTableModel) (jTable2.getModel());
                model.addRow(new Object[]{i, d, e, f, h});
            }

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_vpMousePressed

    private void dpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dpMousePressed
        addp.setBackground(new Color(153, 153, 153));
        upp.setBackground(new Color(153, 153, 153));
        vp.setBackground(new Color(153, 153, 153));
        dp.setBackground(new Color(204, 204, 204));

        addL.setVisible(false);
        updateL.setVisible(false);
        viewL.setVisible(false);
        deleteL.setVisible(true);
    }//GEN-LAST:event_dpMousePressed

    private void addButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtActionPerformed
        try {
            int pno = Integer.parseInt(pno1.getText());
            String pname = pname1.getText();
            String sdate = sdate1.getText();
            int duration = Integer.parseInt(du1.getText());
            double price = Double.parseDouble(price1.getText());

            String mainquery = "insert into postgraduate values (" + pno + ",'" + pname + "','" + sdate + "'," + duration + "," + price + ")";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/New_Database", "root", "ng1996kt");

            Statement stmt = con.createStatement();
            stmt.executeUpdate(mainquery);

            JOptionPane.showMessageDialog(null, "Program Added Sucessfull");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        pno1.setText("");
        pname1.setText("");
        sdate1.setText("");
        du1.setText("");
        price1.setText("");
    }//GEN-LAST:event_addButtActionPerformed

    private void deleteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButActionPerformed
        try {
            int delt = Integer.parseInt(deletepr.getText());

            String query = "delete from postgraduate where pno=" + delt + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/New_Database", "root", "ng1996kt");

            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);

            JOptionPane.showMessageDialog(null, "Program Deleted Sucessfull");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        deletepr.setText("");
    }//GEN-LAST:event_deleteButActionPerformed

    private void jButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt1ActionPerformed
        try {

            int i = Integer.parseInt(pid1.getText());
            String n = uname1.getText();

            String quary = "update postgraduate set pname ='" + n + "'where pno =" + i + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/New_Database", "root", "ng1996kt");

            Statement stmt = con.createStatement();
            stmt.executeUpdate(quary);

            JOptionPane.showMessageDialog(null, "Name Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        pid1.setText("");
        uname1.setText("");
    }//GEN-LAST:event_jButt1ActionPerformed

    private void jButt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt2ActionPerformed
        try {

            int i = Integer.parseInt(pid1.getText());
            String n = usdate1.getText();

            String quary = "update postgraduate set sdate ='" + n + "'where pno =" + i + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/New_Database", "root", "ng1996kt");

            Statement stmt = con.createStatement();
            stmt.executeUpdate(quary);

            JOptionPane.showMessageDialog(null, "Date Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        pid1.setText("");
        usdate1.setText("");
    }//GEN-LAST:event_jButt2ActionPerformed

    private void jButt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt3ActionPerformed
                               try {

            int i = Integer.parseInt(pid1.getText());
            int n= Integer.parseInt(udu1.getText());

            String quary = "update postgraduate set duration ='" + n + "'where pno =" + i + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/New_Database", "root", "ng1996kt");

            Statement stmt = con.createStatement();
            stmt.executeUpdate(quary);

            JOptionPane.showMessageDialog(null, "Duration Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        pid1.setText("");
        udu1.setText("");
    }//GEN-LAST:event_jButt3ActionPerformed

    private void jButt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButt4ActionPerformed
                                       try {

            int i = Integer.parseInt(pid1.getText());
            int n= Integer.parseInt(upri1.getText());

            String quary = "update postgraduate set price ='" + n + "'where pno =" + i + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/New_Database", "root", "ng1996kt");

            Statement stmt = con.createStatement();
            stmt.executeUpdate(quary);

            JOptionPane.showMessageDialog(null, "Price Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        pid1.setText("");
        upri1.setText("");
    }//GEN-LAST:event_jButt4ActionPerformed

    private void close1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close1ActionPerformed

    private void close2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close2ActionPerformed

    private void close3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close3ActionPerformed

    private void close4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(managePostgraduateprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(managePostgraduateprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(managePostgraduateprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(managePostgraduateprogram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new managePostgraduateprogram().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButt;
    private javax.swing.JPanel addL;
    private javax.swing.JPanel addp;
    private javax.swing.JButton close1;
    private javax.swing.JButton close2;
    private javax.swing.JButton close3;
    private javax.swing.JButton close4;
    private javax.swing.JButton deleteBut;
    private javax.swing.JPanel deleteL;
    private javax.swing.JTextField deletepr;
    private javax.swing.JPanel dp;
    private javax.swing.JTextField du1;
    private javax.swing.JButton jButt1;
    private javax.swing.JButton jButt2;
    private javax.swing.JButton jButt3;
    private javax.swing.JButton jButt4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel mid;
    private javax.swing.JTextField pid1;
    private javax.swing.JTextField pname1;
    private javax.swing.JTextField pno1;
    private javax.swing.JTextField price1;
    private javax.swing.JLabel prog1;
    private javax.swing.JLabel prog10;
    private javax.swing.JLabel prog11;
    private javax.swing.JLabel prog12;
    private javax.swing.JLabel prog13;
    private javax.swing.JLabel prog14;
    private javax.swing.JLabel prog2;
    private javax.swing.JLabel prog3;
    private javax.swing.JLabel prog4;
    private javax.swing.JLabel prog5;
    private javax.swing.JLabel prog7;
    private javax.swing.JLabel prog9;
    private javax.swing.JLabel progl1;
    private javax.swing.JLabel progl2;
    private javax.swing.JLabel progl3;
    private javax.swing.JLabel prol6;
    private javax.swing.JTextField sdate1;
    private javax.swing.JTextField udu1;
    private javax.swing.JTextField uname1;
    private javax.swing.JPanel updateL;
    private javax.swing.JPanel upp;
    private javax.swing.JTextField upri1;
    private javax.swing.JTextField usdate1;
    private javax.swing.JLabel vLabel7;
    private javax.swing.JPanel viewL;
    private javax.swing.JPanel vp;
    // End of variables declaration//GEN-END:variables
}
