/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DatabaseLayer.DbConnection;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kavishna
 */
public class manageUndergraduateprograms extends javax.swing.JFrame {

    /**
     * Creates new form managendergraduateprograms
     */
    public manageUndergraduateprograms() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        view = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        delete = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        update = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        midLayer = new javax.swing.JPanel();
        addLayer = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pid = new javax.swing.JTextField();
        pnm = new javax.swing.JTextField();
        sd = new javax.swing.JTextField();
        dr = new javax.swing.JTextField();
        pr = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        close5 = new javax.swing.JButton();
        formatd2 = new javax.swing.JLabel();
        updateLayer = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        upno = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        udate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        uduration = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        uprice = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        Updatename = new javax.swing.JButton();
        updateDate = new javax.swing.JButton();
        updateDuration = new javax.swing.JButton();
        updatePrice = new javax.swing.JButton();
        close6 = new javax.swing.JButton();
        viewLayer = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        close7 = new javax.swing.JButton();
        deleteLayer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        deletep = new javax.swing.JTextField();
        dlt = new javax.swing.JButton();
        close8 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        add.setBackground(new java.awt.Color(153, 153, 153));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                addMousePressed(evt);
            }
        });

        jLabel9.setText("Add program");

        javax.swing.GroupLayout addLayout = new javax.swing.GroupLayout(add);
        add.setLayout(addLayout);
        addLayout.setHorizontalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        addLayout.setVerticalGroup(
            addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        view.setBackground(new java.awt.Color(153, 153, 153));
        view.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                viewMousePressed(evt);
            }
        });

        jLabel10.setText("View program");

        javax.swing.GroupLayout viewLayout = new javax.swing.GroupLayout(view);
        view.setLayout(viewLayout);
        viewLayout.setHorizontalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        viewLayout.setVerticalGroup(
            viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        delete.setBackground(new java.awt.Color(153, 153, 153));
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                deleteMousePressed(evt);
            }
        });

        jLabel11.setText("Delete program");

        javax.swing.GroupLayout deleteLayout = new javax.swing.GroupLayout(delete);
        delete.setLayout(deleteLayout);
        deleteLayout.setHorizontalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        deleteLayout.setVerticalGroup(
            deleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        update.setBackground(new java.awt.Color(153, 153, 153));
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                updateMousePressed(evt);
            }
        });

        jLabel4.setText("Update program");

        javax.swing.GroupLayout updateLayout = new javax.swing.GroupLayout(update);
        update.setLayout(updateLayout);
        updateLayout.setHorizontalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        updateLayout.setVerticalGroup(
            updateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        midLayer.setBackground(new java.awt.Color(204, 204, 204));
        midLayer.setLayout(new java.awt.CardLayout());

        addLayer.setBackground(new java.awt.Color(204, 204, 204));

        jLabel5.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        jLabel5.setText("Add new  undergraduate degree program");

        jLabel1.setText("Program No");

        jLabel2.setText("Program Name");

        jLabel3.setText("Strating Date");

        jLabel12.setText("Duration");

        jLabel13.setText("Price");

        pid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidActionPerformed(evt);
            }
        });

        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        close5.setText("Close");
        close5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close5ActionPerformed(evt);
            }
        });

        formatd2.setText("YYYY-MM-DD");

        javax.swing.GroupLayout addLayerLayout = new javax.swing.GroupLayout(addLayer);
        addLayer.setLayout(addLayerLayout);
        addLayerLayout.setHorizontalGroup(
            addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayerLayout.createSequentialGroup()
                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addLayerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addLayerLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(addButton)
                            .addGroup(addLayerLayout.createSequentialGroup()
                                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(55, 55, 55)
                                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dr, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                                    .addComponent(pnm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pid, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pr)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addLayerLayout.createSequentialGroup()
                                        .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(formatd2))))
                            .addComponent(close5))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        addLayerLayout.setVerticalGroup(
            addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(22, 22, 22)
                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formatd2))
                .addGap(18, 18, 18)
                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(dr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(close5)
                .addContainerGap())
        );

        midLayer.add(addLayer, "card2");

        updateLayer.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        jLabel6.setText("Update  undergraduate degree program");

        jLabel14.setText("Program No");

        upno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upnoActionPerformed(evt);
            }
        });

        jLabel15.setText(" Update Program Name");

        jLabel16.setText(" Update Strating Date");

        jLabel17.setText(" Update Duration");

        jLabel18.setText(" Update Price");

        jLabel19.setText("Enter program no where you want to make a change");

        Updatename.setText("Update");
        Updatename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatenameActionPerformed(evt);
            }
        });

        updateDate.setText("Update");
        updateDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDateActionPerformed(evt);
            }
        });

        updateDuration.setText("Update");
        updateDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateDurationActionPerformed(evt);
            }
        });

        updatePrice.setText("Update");
        updatePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePriceActionPerformed(evt);
            }
        });

        close6.setText("Close");

        javax.swing.GroupLayout updateLayerLayout = new javax.swing.GroupLayout(updateLayer);
        updateLayer.setLayout(updateLayerLayout);
        updateLayerLayout.setHorizontalGroup(
            updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayerLayout.createSequentialGroup()
                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateLayerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(updateLayerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateLayerLayout.createSequentialGroup()
                                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addGap(49, 49, 49)
                                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(upno, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(updateLayerLayout.createSequentialGroup()
                                        .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(uprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                            .addComponent(uduration, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(udate, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(uname, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Updatename)
                                            .addComponent(updateDate)
                                            .addComponent(updateDuration)
                                            .addComponent(updatePrice)
                                            .addComponent(close6))))))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        updateLayerLayout.setVerticalGroup(
            updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(18, 18, 18)
                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(upno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Updatename))
                .addGap(47, 47, 47)
                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(udate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateDate))
                .addGap(45, 45, 45)
                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(uduration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateDuration)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(updateLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatePrice))
                .addGap(51, 51, 51)
                .addComponent(close6)
                .addContainerGap())
        );

        midLayer.add(updateLayer, "card3");

        viewLayer.setBackground(new java.awt.Color(204, 204, 204));

        jLabel7.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        jLabel7.setText("View undergraduate degree programs");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Program No", "Program Name", "Starting Date", "Duration", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        close7.setText("Close");
        close7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout viewLayerLayout = new javax.swing.GroupLayout(viewLayer);
        viewLayer.setLayout(viewLayerLayout);
        viewLayerLayout.setHorizontalGroup(
            viewLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(viewLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(viewLayerLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, viewLayerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(close7))
        );
        viewLayerLayout.setVerticalGroup(
            viewLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(close7))
        );

        midLayer.add(viewLayer, "card4");

        deleteLayer.setBackground(new java.awt.Color(204, 204, 204));

        jLabel8.setFont(new java.awt.Font("STIXIntegralsSm", 0, 24)); // NOI18N
        jLabel8.setText("Delete undergraduate degree program");

        jLabel20.setText("Enter Progam no you want to delete");

        jLabel21.setText("Program No");

        dlt.setText("Delete");
        dlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dltActionPerformed(evt);
            }
        });

        close8.setText("Close");
        close8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout deleteLayerLayout = new javax.swing.GroupLayout(deleteLayer);
        deleteLayer.setLayout(deleteLayerLayout);
        deleteLayerLayout.setHorizontalGroup(
            deleteLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(deleteLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(deleteLayerLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(26, 26, 26)
                        .addComponent(deletep, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dlt)))
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, deleteLayerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(close8)
                .addGap(28, 28, 28))
        );
        deleteLayerLayout.setVerticalGroup(
            deleteLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(deleteLayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jLabel20)
                .addGap(37, 37, 37)
                .addGroup(deleteLayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(deletep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dlt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 343, Short.MAX_VALUE)
                .addComponent(close8)
                .addContainerGap())
        );

        midLayer.add(deleteLayer, "card5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(midLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(midLayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMousePressed
        add.setBackground(new Color(204, 204, 204));
        update.setBackground(new Color(153, 153, 153));
        view.setBackground(new Color(153, 153, 153));
        delete.setBackground(new Color(153, 153, 153));

        addLayer.setVisible(true);
        updateLayer.setVisible(false);
        viewLayer.setVisible(false);
        deleteLayer.setVisible(false);
    }//GEN-LAST:event_addMousePressed

    private void updateMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMousePressed
        add.setBackground(new Color(153, 153, 153));
        update.setBackground(new Color(204, 204, 204));
        view.setBackground(new Color(153, 153, 153));
        delete.setBackground(new Color(153, 153, 153));

        addLayer.setVisible(false);
        updateLayer.setVisible(true);
        viewLayer.setVisible(false);
        deleteLayer.setVisible(false);
    }//GEN-LAST:event_updateMousePressed

    private void viewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewMousePressed
        add.setBackground(new Color(153, 153, 153));
        update.setBackground(new Color(153, 153, 153));
        view.setBackground(new Color(204, 204, 204));
        delete.setBackground(new Color(153, 153, 153));

        addLayer.setVisible(false);
        updateLayer.setVisible(false);
        viewLayer.setVisible(true);
        deleteLayer.setVisible(false);

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DbConnection.getConnection();

            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from undergraduate");
            DefaultTableModel clear = (DefaultTableModel) (jTable1.getModel());
            clear.setRowCount(0);

            while (rs.next()) {
                int i = rs.getInt(1);
                String d = rs.getString(2);
                String e = rs.getString(3);
                String f = rs.getString(4);
                String h = rs.getString(5);
                DefaultTableModel model = (DefaultTableModel) (jTable1.getModel());
                model.addRow(new Object[]{i, d, e, f, h});
            }

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_viewMousePressed

    private void deleteMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMousePressed
        add.setBackground(new Color(153, 153, 153));
        update.setBackground(new Color(153, 153, 153));
        view.setBackground(new Color(153, 153, 153));
        delete.setBackground(new Color(204, 204, 204));

        addLayer.setVisible(false);
        updateLayer.setVisible(false);
        viewLayer.setVisible(false);
        deleteLayer.setVisible(true);
    }//GEN-LAST:event_deleteMousePressed

    private void pidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        try {
            int pno = Integer.parseInt(pid.getText());
            String pname = pnm.getText();
            String sdate = sd.getText();
            int duration = Integer.parseInt(dr.getText());
            double price = Double.parseDouble(pr.getText());

            String mainquery = "insert into undergraduate values (" + pno + ",'" + pname + "','" + sdate + "'," + duration + "," + price + ")";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DbConnection.getConnection();

            Statement stmt = con.createStatement();
            stmt.executeUpdate(mainquery);

            JOptionPane.showMessageDialog(null, "Program Added Sucessfull");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        pid.setText("");
        pnm.setText("");
        sd.setText("");
        dr.setText("");
        pr.setText("");
    }//GEN-LAST:event_addButtonActionPerformed

    private void upnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_upnoActionPerformed

    private void UpdatenameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatenameActionPerformed
        try {

            int i = Integer.parseInt(upno.getText());
            String n = uname.getText();

            String quary = "update undergraduate set pname ='" + n + "'where pno =" + i + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DbConnection.getConnection();

            Statement stmt = con.createStatement();
            stmt.executeUpdate(quary);

            JOptionPane.showMessageDialog(null, "Name Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        upno.setText("");
        uname.setText("");


    }//GEN-LAST:event_UpdatenameActionPerformed

    private void updateDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDateActionPerformed
        try {

            int i = Integer.parseInt(upno.getText());
            String n = udate.getText();

            String quary = "update undergraduate set sdate ='" + n + "'where pno =" + i + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DbConnection.getConnection();

            Statement stmt = con.createStatement();
            stmt.executeUpdate(quary);

            JOptionPane.showMessageDialog(null, "Date Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        upno.setText("");
        udate.setText("");


    }//GEN-LAST:event_updateDateActionPerformed

    private void updateDurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateDurationActionPerformed
        try {

            int pno = Integer.parseInt(upno.getText());
            int duration = Integer.parseInt(uduration.getText());

            //String quary ="update undergraduate set duration = "+duration+"where pno ="+pno+"";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DbConnection.getConnection();

            Statement stmt = con.createStatement();
            int count = stmt.executeUpdate("update undergraduate set duration = '"+duration+"'where pno ="+pno+"");

            JOptionPane.showMessageDialog(null, "Duration Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        upno.setText("");
        uduration.setText("");


    }//GEN-LAST:event_updateDurationActionPerformed

    private void updatePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePriceActionPerformed
        try {

            int i = Integer.parseInt(upno.getText());
            int n = Integer.parseInt(uprice.getText());

            String quary = "update undergraduate set price ='" + n + "'where pno =" + i + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DbConnection.getConnection();

            Statement stmt = con.createStatement();
            int count = stmt.executeUpdate(quary);

            JOptionPane.showMessageDialog(null, "Price Updated");

            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }

        upno.setText("");
        uprice.setText("");

        //JOptionPane.showMessageDialog(null, "Price Updated");
    }//GEN-LAST:event_updatePriceActionPerformed

    private void dltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dltActionPerformed
        try {
            int delt = Integer.parseInt(deletep.getText());

            String query = "delete from undergraduate where pno=" + delt + "";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DbConnection.getConnection();

            Statement stmt = con.createStatement();
            stmt.executeUpdate(query);

            

        JOptionPane.showMessageDialog(null, "Program Deleted Sucessfull");
            
            con.close();
        } catch (Exception e) {
            System.out.println(e);
        }
        
        deletep.setText("");
    }//GEN-LAST:event_dltActionPerformed

    private void close5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close5ActionPerformed

    private void close7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close7ActionPerformed

    private void close8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_close8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(manageUndergraduateprograms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(manageUndergraduateprograms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(manageUndergraduateprograms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(manageUndergraduateprograms.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new manageUndergraduateprograms().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Updatename;
    private javax.swing.JPanel add;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel addLayer;
    private javax.swing.JButton close5;
    private javax.swing.JButton close6;
    private javax.swing.JButton close7;
    private javax.swing.JButton close8;
    private javax.swing.JPanel delete;
    private javax.swing.JPanel deleteLayer;
    private javax.swing.JTextField deletep;
    private javax.swing.JButton dlt;
    private javax.swing.JTextField dr;
    private javax.swing.JLabel formatd2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel midLayer;
    private javax.swing.JTextField pid;
    private javax.swing.JTextField pnm;
    private javax.swing.JTextField pr;
    private javax.swing.JTextField sd;
    private javax.swing.JTextField udate;
    private javax.swing.JTextField uduration;
    private javax.swing.JTextField uname;
    private javax.swing.JPanel update;
    private javax.swing.JButton updateDate;
    private javax.swing.JButton updateDuration;
    private javax.swing.JPanel updateLayer;
    private javax.swing.JButton updatePrice;
    private javax.swing.JTextField upno;
    private javax.swing.JTextField uprice;
    private javax.swing.JPanel view;
    private javax.swing.JPanel viewLayer;
    // End of variables declaration//GEN-END:variables
}
